#!/bin/bash

MERLKE_EBIN=$(dirname $(readlink $0))/../ebin
MERLKE_DIR=$(pwd)
MERLKE_WORKSPACE=/tmp/merlke_$(echo -n "$MERLKE_DIR" | md5)
COMPILE_ERROR_LOG=$MERLKE_WORKSPACE/compile.log
NOSHELL="-noshell"

ARGS=$(getopt s $*)
if [ $? != 0 ]
then
       echo 'Usage: merlke [-s] [task1 [task2 [task3 [...]]]]'
       exit 2
fi
set -- $ARGS

for i
do
       case "$i"
       in
               -s)
                       NOSHELL=""
                       shift;;
               --)
                       shift; break;;
       esac
done


mkdir -p "$MERLKE_WORKSPACE"
rm -f "$COMPILE_ERROR_LOG"

if [ -e $MERLKE_DIR/merlkefile.erl ]
then
    erlc -o "$MERLKE_WORKSPACE" $MERLKE_DIR/merlkefile.erl 2>&1 > "$COMPILE_ERROR_LOG"

    if [ "$?" != "0" ] 
    then
        cat $MERLKE_WORKSPACE/compile.log
        exit 1
    fi
fi

erl -pa "$MERLKE_EBIN"            \
    -pa "$MERLKE_WORKSPACE"       \
    -pa deps/*/ebin               \
    -pa ebin                      \
    $NOSHELL                      \
    -run merlke_runner execute $@ \
    -run init stop



